services:
  - type: web
    name: itda-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APP_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
